- no /dev on builders - rel 3

diff --git a/tests.patch b/tests.patch
--- a/tests.patch
+++ b/tests.patch
@@ -120,3 +120,36 @@
  if test $double_slash = //; then
    test "$out" = "/$nl//" || fail=1
  else
+--- coreutils-8.21/tests/misc/nohup.sh~	2013-01-31 01:46:24.000000000 +0100
++++ coreutils-8.21/tests/misc/nohup.sh	2013-12-03 13:35:51.952568924 +0100
+@@ -61,18 +61,18 @@
+ 
+ # Bug present through coreutils 8.0: failure to print advisory message
+ # to stderr must be fatal.  Requires stdout to be terminal.
+-if test -w /dev/full && test -c /dev/full; then
+-(
+-  exec >/dev/tty
+-  test -t 1 || exit 0
+-  nohup echo hi 2> /dev/full
+-  test $? = 125 || fail=1
+-  test -f nohup.out || fail=1
+-  test -s nohup.out && fail=1
+-  rm -f nohup.out
+-  exit $fail
+-) || fail=1
+-fi
++#if test -w /dev/full && test -c /dev/full; then
++#(
++#  exec >/dev/tty
++#  test -t 1 || exit 0
++#  nohup echo hi 2> /dev/full
++#  test $? = 125 || fail=1
++#  test -f nohup.out || fail=1
++#  test -s nohup.out && fail=1
++#  rm -f nohup.out
++#  exit $fail
++#) || fail=1
++#fi
+ 
+ nohup no-such-command 2> err
+ errno=$?
